version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  web-app:
    build: ./web-app
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/flaskdb
      - SECRET_KEY=supersecretkey
    depends_on:
      - mongodb
  machine-learning-client:
    build: ./machine-learning-client
    environment:
      - MONGO_URI=mongodb://mongodb:27017/flaskdb
      - SECRET_KEY=supersecretkey
    ports:
      - "5001:5001"

