name: Keter Class Machine Learning Test
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10"]
    steps:
      - name: Checkout Repo to Actions Runner
        uses: actions/checkout@v4
      - name: Install Python 
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Create test images directory
        run: |
          mkdir -p machine-learning-client/images
          # Create empty placeholder image files
          touch machine-learning-client/images/card1.png
          touch machine-learning-client/images/card2.png
          touch machine-learning-client/images/card3.png
      - name: Install pipenv
        run: pip install pipenv
      - name: Test Machine Learning Client
        working-directory: machine-learning-client
        env:
          PYTEST_CURRENT_TEST: "True"
        run: |
          pipenv install pytest pytest-mock
          pipenv install
          pipenv run python -m pytest