name: Keter Class Web App Testing
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10"]
    steps:
      - name: Checkout Repo to Actions Runner
        uses: actions/checkout@v4
      - name: Install Python 
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install pipenv
        run: pip install pipenv
      - name: Test Web App
        working-directory: web_app
        run: |
          pipenv install pytest
          pipenv --venv
          pipenv install
          pipenv run python -m pytest